name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build containers
        run: docker-compose -f compose.yaml build

      - name: Run containers
        run: docker-compose -f compose.yaml up -d

      - name: Stop containers
        run: docker-compose -f compose.yaml down
